### ISSUE TITLE
drill installation (MacOS)

### ISSUE THREAD

**Issue by espinielli** [hrbrmstr/drill-sergeant-rstats#6]
In chapter 4 it says:
> On Linux and macOS, it’s best to have drill in /usr/local/drill (it’s handy to symlink the full versioned directory to drill to make it easier to switch out/upgrade versions)

I have installed the latest `drill` via homebrew, the file tree as mentioned in the book are in
`/usr/local/Cellar/apache-drill/1.13.0/libexec`.

What should I have to do more if ? A symlink like

```bash
$ ln -s /usr/local/Cellar/apache-drill/1.13.0/libexec /usr/local/drill
```
(`brew doctor` will complain but I will probably remember why ;-)

Then which commands should I use, the ones in `/usr/local/Cellar/apache-drill/1.13.0/libexec/bin`
or the ones in `/usr/local/Cellar/apache-drill/1.13.0/bin`?
The have the same name but different content...

Please advise (which could well be a redirection to some manual page/doc that I failed to read ;-)
Thank you in advance for considering this

**Comment by hrbrmstr** [comment]
I'll have to revise this for homebrew installers. For a while there was no homebrew drill recipe but i'm rly glad @alistaire47 got one in there.

for homebrew users there shld be no need to change anything, save for the location of the third party jars (which will be in the homebrew loc)

**Comment by espinielli** [comment]
I am not able to go beyond section 0.4 (sorry above I mentioned "chapter 4"!)

If I translate the description to my installation I have
* change `drill-override.conf` in `/usr/local/Cellar/apache-drill/1.13.0/conf/` as explained (I put my own `cluster-id`)
* execute `$ /usr/local/Cellar/apache-drill/1.13.0/bin/drillbit.sh start`

but I get
```
/usr/local/Cellar/apache-drill/1.13.0/bin/drillbit.sh start
/usr/local/Cellar/apache-drill/1.13.0/libexec/bin/drill-config.sh: line 141: let: lineCount=: syntax error: operand expected (error token is "=")
/usr/local/Cellar/apache-drill/1.13.0/libexec/bin/drill-config.sh: line 141: let: lineCount=: syntax error: operand expected (error token is "=")
/usr/local/Cellar/apache-drill/1.13.0/libexec/bin/drill-config.sh: line 141: let: lineCount=: syntax error: operand expected (error token is "=")
/usr/local/Cellar/apache-drill/1.13.0/libexec/bin/drill-config.sh: line 141: let: lineCount=: syntax error: operand expected (error token is "=")
Starting drillbit, logging to /usr/local/Cellar/apache-drill/1.13.0/libexec/log/drillbit.out
```

* test via `$ /usr/local/Cellar/apache-drill/1.13.0/bin/drill-conf`
and get 

```
Error: Failure in connecting to Drill: org.apache.drill.exec.rpc.RpcException: CONNECTION : io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: controller/195.154.179.210:31010 (state=,code=0)
java.sql.SQLNonTransientConnectionException: Failure in connecting to Drill: org.apache.drill.exec.rpc.RpcException: CONNECTION : io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: controller/195.154.179.210:31010
	at org.apache.drill.jdbc.impl.DrillConnectionImpl.<init>(DrillConnectionImpl.java:179)
	at org.apache.drill.jdbc.impl.DrillJdbc41Factory.newDrillConnection(DrillJdbc41Factory.java:73)
	at org.apache.drill.jdbc.impl.DrillFactory.newConnection(DrillFactory.java:69)
	at org.apache.calcite.avatica.UnregisteredDriver.connect(UnregisteredDriver.java:138)
	at org.apache.drill.jdbc.Driver.connect(Driver.java:72)
	at sqlline.DatabaseConnection.connect(DatabaseConnection.java:168)
	at sqlline.DatabaseConnection.getConnection(DatabaseConnection.java:214)
	at sqlline.Commands.connect(Commands.java:1083)
	at sqlline.Commands.connect(Commands.java:1015)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sqlline.ReflectiveCommandHandler.execute(ReflectiveCommandHandler.java:36)
	at sqlline.SqlLine.dispatch(SqlLine.java:742)
	at sqlline.SqlLine.initArgs(SqlLine.java:528)
	at sqlline.SqlLine.begin(SqlLine.java:596)
	at sqlline.SqlLine.start(SqlLine.java:375)
	at sqlline.SqlLine.main(SqlLine.java:268)
Caused by: org.apache.drill.exec.rpc.RpcException: CONNECTION : io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: controller/195.154.179.210:31010
	at org.apache.drill.exec.rpc.user.UserClient$2.connectionFailed(UserClient.java:315)
	at org.apache.drill.exec.rpc.user.QueryResultHandler$ChannelClosedHandler.connectionFailed(QueryResultHandler.java:389)
	at org.apache.drill.exec.rpc.ConnectionMultiListener$ConnectionHandler.operationComplete(ConnectionMultiListener.java:119)
	at org.apache.drill.exec.rpc.ConnectionMultiListener$ConnectionHandler.operationComplete(ConnectionMultiListener.java:77)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:278)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:294)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: controller/195.154.179.210:31010
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:54)
	at org.apache.drill.exec.rpc.ConnectionMultiListener$ConnectionHandler.operationComplete(ConnectionMultiListener.java:90)
	... 13 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: controller/195.154.179.210:31010
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:258)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
	... 6 more
Caused by: java.net.ConnectException: Connection refused
	... 10 more
apache drill 1.13.0
"say hello to my little drill"
0: jdbc:drill:>
```

and no real connection...
Any directions welcome.

**Comment by espinielli** [comment]
The issue is with the loopback: if I disable the (corporate w/ proxy authentication) WIFI, I can successfully run drill...
I haven't been able to find how to have it work with WIFI enabled as of now...

**Comment by AceHack** [comment]
Have similar issue, how can I force to use 127.0.0.1
